server:
  port: ${PORT:9898}

spring:
  application:
    name: react-spring-boot-keycloak-authentication

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8989/realms/springboot-test}

app:
  oauth2-client-name: react-app
  cors:
    urls:
      - http://localhost:5173
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    headers:
      - "*"